1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [2]:
import numpy as np

In [5]:
m = np.arange(12).reshape((3,4))
mean = np.mean(m)

mean_r =[np.mean(m[i,:]) for i in range(3)]
mean_c = [np.mean(m[:,i]) for i in range(4)]

print(mean_c)
print(mean_r)

[4.0, 5.0, 6.0, 7.0]
[1.5, 5.5, 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [21]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
outer = np.outer(u,v)
print(outer)

m = np.zeros((4,4))
for i in range(len(u)):
    for j in range(len(u)):
        m[i][j] = u[i]*v[j]        
print(m)

vt = v.reshape((4,1))
prod = u*vt
print(prod.T)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [3]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# Using the function outer in numpy
out_prod = np.outer(u,v)

# Using a nested for loop or a list comprehension

out_prod1 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        out_prod1[i,j] =int( u[i]*v[j])
        
#Using numpy broadcasting operations

u = u.reshape(4,1)
out_prod2 = u*v
        
        

print(out_prod, out_prod1, out_prod2)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]] [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [25]:
import random

m= np.random.uniform(0,3, size = (10,6))

mask = (m<0.3)
m[mask] == 0
print(m)

[[0.8624673  0.20009313 1.64221385 1.60387054 2.56706642 0.42059189]
 [1.13690278 0.94604281 0.41315219 0.38182217 2.13493544 1.91559643]
 [2.75689106 2.75681873 2.07303165 1.62840791 0.20632192 2.24003406]
 [2.31748104 2.3505581  0.08465252 2.95728699 2.68005658 1.19982599]
 [1.86073868 1.72172208 1.14065503 2.77461143 2.30649594 2.85065899]
 [2.88458467 1.87803482 0.93875103 2.79778631 2.77263612 2.99304862]
 [2.36335719 1.69114112 0.96311415 1.67082804 1.68833701 2.28534664]
 [2.61771527 0.52728932 2.33439418 1.05360178 2.74992302 0.18292855]
 [0.86291708 1.67871138 0.07921062 2.36434815 0.97126513 2.03540102]
 [0.7644082  2.22934079 0.30245368 1.37973958 1.68290599 1.82571712]]


In [27]:
m = np.random.uniform(0,3, size = (10,6))

print(m)

m[m < 0.3] = 0
print(m)

[[2.23404161 0.55202651 2.43169911 2.13607673 0.22577102 1.55674151]
 [2.03980543 1.31144468 0.62036984 1.40193238 0.39972761 2.846401  ]
 [0.30219851 0.24021158 0.75746628 0.10604354 2.71973155 1.68270918]
 [2.71006234 0.42401187 2.61166618 1.16989037 0.540157   2.48473074]
 [2.34355724 1.93510771 2.68871957 0.78082318 2.21894069 2.95573293]
 [2.32103936 2.90974763 1.7799524  1.38232104 2.96930517 0.624361  ]
 [1.87142169 2.60955611 2.72675993 1.81548104 0.0303829  2.98903571]
 [2.62595613 1.6630459  0.09500524 2.46072511 2.76751605 0.5143194 ]
 [2.96273514 0.93088443 0.54101127 2.96873649 1.2733553  1.58886237]
 [0.41164758 0.36919451 2.93259545 0.13338971 0.90073048 1.07794014]]
[[2.23404161 0.55202651 2.43169911 2.13607673 0.         1.55674151]
 [2.03980543 1.31144468 0.62036984 1.40193238 0.39972761 2.846401  ]
 [0.30219851 0.         0.75746628 0.         2.71973155 1.68270918]
 [2.71006234 0.42401187 2.61166618 1.16989037 0.540157   2.48473074]
 [2.34355724 1.93510771 2.6887195

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [35]:
import math 
m = np.linspace(0,2*math.pi,100)
sl = m[::10]
sl
reverse =sl[::-1]
print(reverse)

mask = np.abs(np.sin(m)-np.cos(m)) < 0.1

m = m[mask]
print(m)

[5.71198664 5.07732146 4.44265628 3.8079911  3.17332591 2.53866073
 1.90399555 1.26933037 0.63466518 0.        ]
[0.76159822 0.82506474 3.87145761 3.93492413]


In [5]:
pi_h = math.pi
m = np.linspace(0, 2* pi_h, 100)

#Extract every 10th element using the slice notation

elementi = m[::10]
print(elementi)

#Reverse the array using the slice notation

reverse = m[::-1]
print(reverse)


#Extract elements where the absolute difference between the sin and cos functions evaluated for that element is  <0.1
mask = (abs(np.sin(m) - np.cos(m)) <0.1)
m_filtrata = m[mask]
print(m_filtrata)

[0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]
[6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 1.45972992 1.3962634
 1.33279688 1.2693

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [46]:
v = np.array([1,2,3,4,5,6,7,8,9,10],dtype= int)
u = np.array([1,2,3,4,5,6,7,8,9,10], dtype= int)

m = np.outer(u,v)
print(m)

tace = np.trace(m)
print(np.diag(np.fliplr(m)))


diag = np.diag(m[:,1:])
print(diag)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[10 18 24 28 30 30 28 24 18 10]
[ 2  6 12 20 30 42 56 72 90]


In [6]:
v = np.array([1,2,3,4,5,6,7,8,9,10],dtype= int)
u = np.array([1,2,3,4,5,6,7,8,9,10], dtype= int).reshape((10,1))

#Find the trace of the matrix
prod = np.zeros((10,10))

for i in range (10):
    for j in range(10):
        prod[i,j] = u[i]*v[j]
        
 
#Extract the anti-diagonal matrix

diag = np.diag(prod)
antidiag = np.diag(np.fliplr(prod))

#xtract the diagonal offset by 1 upwards 
#elimino la prima colonna e prendo la diagonale

prod1 = prod.copy()
prod1 = prod1[:,1:]
diag1 = np.diag(prod1)


print(prod)
print(antidiag)
print(diag1)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
[10. 18. 24. 28. 30. 30. 28. 24. 18. 10.]
[ 2.  6. 12. 20. 30. 42. 56. 72. 90.]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [50]:
city = np.array (["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"])

distanza = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

distanza_km = distanza*1.60934

m = np.stack((distanza_km, city))
print(m)

[['0.0' '318.64932' '487.63002' '1184.47424' '1401.73514' '1890.9745'
  '2373.7765' '2484.82096' '3078.6674199999998' '3939.66432']
 ['Chicago' 'Springfield' 'Saint-Louis' 'Tulsa' 'Oklahoma City'
  'Amarillo' 'Santa Fe' 'Albuquerque' 'Flagstaff' 'Los Angeles']]


In [49]:
city = np.array (["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"])

distanza = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

distanza_km = distanza*1.60934

route_66 = np.stack((city,distanza))

#1 mile = 1.60934 kilometers

route_66_km = np.stack((distanza_km,city))

print(route_66)
print(route_66_km)

[['Chicago' 'Springfield' 'Saint-Louis' 'Tulsa' 'Oklahoma City'
  'Amarillo' 'Santa Fe' 'Albuquerque' 'Flagstaff' 'Los Angeles']
 ['0' '198' '303' '736' '871' '1175' '1475' '1544' '1913' '2448']]
[['0.0' '318.64932' '487.63002' '1184.47424' '1401.73514' '1890.9745'
  '2373.7765' '2484.82096' '3078.6674199999998' '3939.66432']
 ['Chicago' 'Springfield' 'Saint-Louis' 'Tulsa' 'Oklahoma City'
  'Amarillo' 'Santa Fe' 'Albuquerque' 'Flagstaff' 'Los Angeles']]


7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [81]:
from time import timeit

N=np.arange(0,100,1)
mask = np.full(100,True)

for i in range(len(N)):
    if N[i]%2 == 0 and N[i]!= 2:
        mask[i]= False

#per tutti gli altri numeri 
for i in range (3, 99):
    for j in range(i+1, 99):
        if N[j]% N[i] == 0:
            mask[j]= False
            

print(N[mask])

[ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83
 89 97 99]


In [8]:
#calcolo i numeri primi
N = 99

def trova_primi(N):
    v = np.arange(N)

#Construct a shape (N,) boolean array, which is the mask
    mask = np.full((N), True)

#Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element

    for i in range (2,N-1):
        for j in range(i+1,N):
            if v[j] % v[i] == 0 :
                mask[j] = False
 
#Apply the mask to obtain an array of ordered prime numbers
    primi = v[mask]
    return primi

#Check the performances (with timeit); how does it scale with N?
num = [N, 1000, 10000]
time =[]

tempo = timeit.timeit(lambda: trova_primi(99), number=1)
time.append(tempo)
tempo1 = timeit.timeit(lambda: trova_primi(1000), number=1)
time.append(tempo1)
tempo2 = timeit.timeit(lambda: trova_primi(10000), number=1)
time.append(tempo2)
#tempo3 = timeit.timeit(lambda: trova_primi(100000), number=1)
#time.append(tempo)
 
print(time) 


#Implement the optimization suggested in the sieve of Eratosthenes

u = np.arange(2,100,1)
mask = np.full((N), True)

p = 2
i =0
j = 1
while i <len(u)-1:
    j = i+1
    while j < len(u):
        if u[j] % u [i] == 0:
            u = np.delete(u,j)
        j +=1
        
    i +=1

            
print(u)    


[0.002569400006905198, 0.30811919999541715, 30.06320939998841]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [9]:
#Use randint to create a 2D array of size  𝑤𝑎𝑙𝑘𝑒𝑟𝑠×𝑠𝑡𝑒𝑝𝑠
#with values -1 or 1
walkers = 1000
steps = 200
campo = npr.randint(0,2, size= (walkers,steps)) *2 -1

#Calculate the walking distances for each walker (e.g. by summing the elements in each row)

walking_distance = np.cumsum(campo, axis = 1)

#Take the square of the previously-obtained array (element-wise)

walking_distance_qu= pow(walking_distance,2)


#Compute the mean of the squared distances at each step (i.e. the mean along the columns)   

#calcolo la media
media =np.mean(walking_distance_qu, axis = 0 )

print(media)    



    


[  1.      2.048   3.136   4.06    5.128   6.136   7.36    8.648   9.568
  10.704  11.368  12.36   13.424  14.288  15.296  16.14   17.264  18.124
  18.96   19.68   20.728  21.652  22.056  23.04   23.64   24.704  25.608
  27.212  28.84   30.204  31.08   31.744  33.152  33.904  35.032  36.156
  37.312  38.356  40.088  40.548  40.96   42.232  43.224  44.384  45.04
  45.448  46.176  46.812  47.584  48.62   50.456  51.772  52.056  53.312
  53.824  54.368  55.248  55.676  57.     57.66   58.6    59.68   60.104
  60.932  62.72   64.004  65.432  66.58   67.168  68.928  70.104  71.664
  72.504  73.82   74.328  75.452  75.968  77.188  78.128  78.468  78.824
  81.072  80.624  82.008  83.344  84.656  86.752  88.172  88.096  87.988
  88.824  89.32   89.744  91.016  92.184  92.716  93.784  94.408  95.312
  97.12   96.96   98.88  100.48  101.288 102.224 101.188 103.384 104.8
 106.024 107.136 107.832 108.184 109.312 110.328 111.688 113.62  115.592
 116.232 118.424 119.392 121.4   123.256 125.032 125.9

In [10]:
print(timeit.timeit(lambda: trova_primi(99), number=1))

0.0038441000506281853
